version: '3.3'
services:
  postgres:
    image: postgres:10.0-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - ./tables:/docker-entrypoint-initdb.d/
      - database:/var/lib/postgresql/data
  redis:
    image: redis:6.2.1-alpine
    ports:
      - '6379:6379'
  web:
    image: node:12-alpine
    command: ['npm', 'run', 'start:dev']
    working_dir: /app
    ports:
      - '3001:3000'
    volumes:
      - .:/app
    links:
      - redis
      - postgres
    environment:
      - DATABASE_HOST=postgres
      - REDIS_HOST=redis
      - GOOGLE_APPLICATION_CREDENTIALS=/app/quickstart-1549468186695-firebase-adminsdk-o9rku-817dc746c9.json
volumes:
  database:
